# JSON 6902 patch: point ExternalSecret to local-store and read from manual-env-secrets
- op: replace
  path: /spec/secretStoreRef/name
  value: local-store
- op: replace
  path: /spec/dataFrom/0/extract/key
  value: manual-env-secrets
