apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ./secrets/auth-service-secrets.yaml
  - ./secrets/users-service-secrets.yaml
  - ./secrets/api-gateway-service-secrets.yaml
  - ./secrets/registry-service-secrets.yaml

patches:
  - target:
      kind: Ingress
      name: api-gateway
    path: ingress-patch.yaml
