apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - secret-store.yaml

patches:
  - target:
      kind: ExternalSecret
      name: config
    path: externalsecret-patch.yaml
  - target:
      kind: Ingress
      name: api-gateway
    path: ingress-patch.yaml
