apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ include "microservice.servicePort" . }}
      targetPort: {{ include "microservice.portName" . }}
      protocol: TCP
      name: {{ include "microservice.portName" . }}
  selector:
    {{- include "microservice.selectorLabels" . | nindent 4 }}
