apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  config.js: |
    window.__ENV__ = {
      API_GATEWAY_URL: {{ .Values.apiGatewayUrl | quote }}
    };
